project:
  type: book
  output-dir: docs

book:
  title: "Crime trends in Finland 2024"
  author: "Janne Kivivuori , Ilari Kolttola, Aaro Beuker, Matti Näsi, Tiina Malin, Anna Raeste, Karoliina Suonpää, Maiju Tanskanen and Miisa Törölä"
  date: "2025-04-25"
  site-url: https://krimo-rt.github.io/crime-trends-in-finland/
  chapters:
    - index.qmd
    - Crime indicators.qmd
    - crime trends.qmd
    - youth crime.qmd
    - alcohol.qmd
    - international comparisons.qmd
    - crime prevention.qmd
    - Abbreviations.qmd
    - references.qmd
bibliography: references.bib
nocite: |
  @*
execute:
  echo: false



format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

