# Alcohol and drugs

Traditionally, the Finnish homicide scene has been heavily connected to drinking group violence among marginalised and unemployed males. The dynamics of homicide has been connected to total alcohol consumption in the long historical perspective [@lehti_henkirikoskatsaus_2020]. However, over the last 20-30 years, the presence of alcohol in homicide has decreased [@lehti_homicide_2014]. A recent analysis of homicide comparing young and adult victims indicated that the young victims (15–29-year-olds) were often under the influence of drugs at the time of the offence, whereas adult victimisation still retained strong links to alcohol use. The same analysis indicated that youth homicide victimisation was more often linked to firearm violence in public places, premeditation, and links to criminal activities [@kivivuori_comparing_2024]. 

Thus, while alcohol retains its high presence in crimes of violence, its role appears to be decreasing. The intoxication status figures of assault and robbery suspects based on official statistics are challenging to interpret, because the category of crimes where the intoxication status is “not known” is large and increasing. However, homicide analyses suggest that the decreasing trend of alcohol is real rather than a statistical artefact. Additional support for this is seen in the FSRD youth crime surveys. They indicate that offending behaviour linked to alcohol, such as drunken driving, has decreased. Similarly, the role of alcohol in physical violence has decreased considerably over the period of two decades [@suonpää2024].
