# Crime prevention

In this section, we present on overview of Finnish crime prevention, with a focus on methods that have received support in robust research evaluations. We draw on the Finnish Crime prevention evaluation database FINPREV, in operation since 2016 [@beuker2024] [@beuker_what_2024], and a recent systematic review on the impact of socioeconomic disadvantage on crime [@suonpää2023]. 

## FINPREV database

Crime prevention methods developed and tested in one social and political context are not necessarily effective elsewhere. It is therefore necessary to conduct and replicate evaluations locally, where they are applied. The FINPREV database was created and is operated by the Institute of Criminology and Legal Policy (KRIMO), University of Helsinki, in cooperation with the Research and Education Division of the National Crime Prevention Council. Launched in 2016, the database compiles studies that empirically assess the effectiveness of crime prevention measures implemented in Finland. It includes research on projects/measures that aim to reduce crime and/or increase public safety. All types of interventions are included, from situational prevention to psycho-social treatment, social policy, and criminal justice sanctions.

The database includes empirical research studies published as articles as well as so-called grey literature (published government and institute reports, and so forth). Of the current original publications included in the database by the end of 2024, 23% were in English, while the rest were published in Finnish. The inclusion of studies is based on the willingness of researchers to include their studies in the database, using a structured online questionnaire developed for this purpose. The database thus standardises the results of studies but does not offer a systematic review of them due to the self-selection of the studies.

The database currently (by the end of 2024) includes 35 evaluated measures, 27 of which are effects assessments of specific measures. Twenty-two of the effects evaluations used research designs at a Maryland 3 level or higher; the information given here is based on those evaluations.

Four measures have been found to be effective in preventing youth crime: (1) the KiVa Koulu bullying prevention programme, (2) the Anchor multiprofessional conferencing teams, targeting offenders under 18 years of age, (3) targeted police supervision of concentrations of high-risk youth engaged in leisure-time activities and (4) participation in secondary education (typically from 15 to 18 years of age).

The other measures supported by research evidence include: (5) opioid replacement treatment, (6) conditional prison terms, and (7) unconditional prison terms. Regarding fines, the studies indicate ambivalent effects: they seem to reduce traffic crimes but may be ineffective or counterproductive more generally. Note that the studies assessing ‘other measures’ did not specify age groups. Their interaction with age or effects among youths, young adults, or other age groups cannot be specified.

Overall, the effective crime prevention methods range from primary to secondary and tertiary measures; based on the studies included, it is not possible to prioritise any of the levels of intervention. More research evaluating effects is needed to assess the effects of crime prevention measures in specific national settings. In Finland, we still lack research on many types of interventions. In particular, little research has been done on social policy actions, community sanctions, and situational crime prevention. Very few of the included studies incorporated estimates of the costs of the intervention: only 26 per cent of all the studies discussed costs. Only one of them included a numerical estimation, whereas the majority only contained reflections on the matter.

## Socioeconomic disadvantage and crime

Recently, [@suonpaa_syrjaytymisen_2023] conducted a systematic review that aimed to assess the evidence on the causal impact of socioeconomic disadvantage on criminal behaviour and victimisation. The review identified 23 Nordic studies that met the methodological criteria for causal analysis. These studies measured socioeconomic disadvantage through multiple indicators: employment status (including job loss and active labor market programs), education, income levels, debt, and neighborhood characteristics.

The most compelling evidence highlighted the importance of employment and education. Job loss increased the risk of criminal behaviour and victimisation, while participation in employment or active labour market programmes reduced these outcomes. Similarly, expanded compulsory education decreased criminal behaviour, whereas limited educational access increased it. Most studies indicated that engagement in employment or education reduced crime through an incapacitation effect, limiting time and opportunities for criminal activity. These findings were robust for property crime but showed mixed results for violent crime. Therefore, the results suggest that both expanding compulsory education and increasing labour market participation may contribute to crime prevention.

The evidence for causal relationships between economic disadvantage or neighbourhood conditions and crime was limited. Therefore, current research does not support identifying these factors as primary causes of criminal behaviour. The observed statistical associations between low income or neighbourhood disadvantage and crime appear to be largely explained by individual characteristics that simultaneously increase the risks of socioeconomic and residential disadvantage, and criminal behaviour and victimisation. However, these conclusions should be interpreted with caution, as they are based on a limited number of causal studies, highlighting the need for additional research with strong causal designs.
