# Crime indicators

In this report, we have drawn on administrative crime statistics and KRIMO crime surveys to describe trends in selected crimes in Finland. The use of administrative statistics and survey data in tandem is mutually complementary. Administrative statistics do not include crimes that have not been not reported to the authorities. The propensity of people to report offences to the police is a temporal and spatial variable. To tackle this challenge, criminology has developed the hidden crime survey [@kivivuori2011] . Unfortunately, such crime surveys typically fail to capture the most serious crimes and the most marginalised offender and victim groups. Furthermore, crime surveys typically produce national estimates, thus overlooking the geographical concentration of crime within local areas. Therefore, this summary report has focused primarily (but not exclusively) on homicide and on crime types for which survey information is available, in order to present a cross-validated overview of recent crime trends. Since the survey indicators do not allow for local trends, we consider Finland as a single observation area in this summary report.

**Administrative statistics of recorded crimes.** The primary source is the Statistics on Offences and Coercive Measures (SOCM), compiled and published by Statistics Finland. In this report, we primarily used figures on offences reported to the police. Figures based on suspects in cleared offences are also needed whenever socio-demographic breakdown is used. In both cases, counts are based on offences as observation units, meaning that a single person may have committed more than one offence per annum. The gross number of offences reported to the police may reflect crime incidence and/or reporting propensity. Except for homicide, attempts are included in the figures. Homicides are additionally examined by cause of death statistics, counting victims of lethal violence.

**Crime surveys.** Regarding crime surveys, we drew on KRIMO key monitoring systems, such as the *Finnish Crime Victim Survey* (FCVS, 1980/2012-) and the *Finnish Self-Report Delinquency Study* (FSRD, 1995-). The *Finnish Crimes against Businesses Survey* (FCBS), conducted in 2010 and 2018, has also been referenced. KRIMO has developed these survey systems by combining international models with methodological research under local conditions [@aaltonen_socioeconomic_2012; @kivivuori_gender_2012; @kivivuori2014; @kaakinen_school_2022].

We have cited selected further research if it provides clarification of observed trends and pattern changes, to allow the interested reader to find more in-depth analyses of the descriptive trends.
