# International comparisons

Making an international comparison of crime rates using administrative statistics is challenging, because legal crime definitions, counting rules, and control practices differ cross-nationally. Therefore, criminologists often prefer homicide statistics and crime surveys for the purposes of comparison.

## Homicide

The Finnish homicide rate has traditionally been higher than is typical in the Nordic area and in Western Europe. Comparison with the other Nordic countries is particularly relevant due to social and cultural similarities, and it reveals that Finland has the highest rate of homicide in the Nordic area [@törölä2024]. In the Finnish homicide report of 2019, 73 per cent of the countries representing the European Economic Area had lower homicide mortality rates than Finland [@lehti2019]. The countries above the Finnish mortality rate were mostly from Eastern Europe.

Regarding trends, a recent study comparing the 1990s homicide drop in Finland with six other European countries found that the substantial drop was observed in all countries, and in both male and female victimisation [@suonpaa_homicide_2022]. In Finland, the relative distribution of homicide types remained stable: the most common homicide type was alcohol-related conflict outside the criminal milieu for men, and family-related homicide for women, whereas homicides taking place within the criminal milieu remained exceptionally rare. The difference was stark with Switzerland, where the typical homicide victim is a woman killed by a family member, and with Sweden, where criminal milieu homicides of young males started to increase in the 2010s.

A recent study of firearm homicide in Europe place Finland and Switzerland as outliers: in these countries, firearm availability is high, yet the prevalence of firearm homicide is relatively low compared to Europe overall [@krusselmann_firearm_2023].

## Victim surveys

The International Crime Victim Surveys (ICVS) were started in 1988 and ended in 2005 [@vandijk2007]. Due to specific sampling difficulties, the results of the last survey, the so-called EU-ICVS conducted in 2003-5, are not reliable for Finland [@aromaa2006]. The four sweeps from 1988 to 1999, with a core group of seven to 12 European countries participating, can be summarised briefly. These surveys suggest that the prevalence of assault or threats was higher than average in Finland. The proportion of countries manifesting lower violence prevalence ranged from 60 to 86 per cent in the four survey waves of 1988-1999 [@van_dijk_criminal_2007]. Personal theft victimisation yields a different picture. Except for the first survey wave in 1988, only a few (9-23 per cent) of the participating countries manifested lower theft victimisation percentages than Finland in the 1991-1999 survey waves. Thus, the ICVS appeared to indicate that Finland was comparatively high on violence and comparatively low on theft during the 1990s.

For theft, we lack more recent international adult victim surveys. In contrast, for violence, some surveys have been conducted. A recent Crime, Safety and Victims’ Rights survey conducted by the European Fundamental Rights Agency showed physical violence victimisation rates in 29 European countries. The comparison placed Finland as the second most violent European nation [@fra2021] after Estonia. Thus, in that survey on physical violence, the proportion of countries ranking lower than Finland was 96 per cent. For Finland, the ICVS sweeps of 1988-1999 and the FRA survey of 2021 both indicated a violence problem at a higher level than is typical in Europe, a finding consistent with homicide rates.

Some EU-wide surveys have been conducted that focus specifically on violence against women. An FRA survey collected in EU countries in 2012 showed high rates of violence against women in Finland and other Nordic countries in comparison to other EU countries. In particular, the rates of both partner and non-partner violence were among the highest in Finland. [@fra2014]. Similar findings have been suggested by the ongoing Eurostat victim survey on violence against women (EU-GBV) collected between 2020 and 2023 in the EU countries. According to the current data of 30 European countries, Finland has above-average rates of violence against women. For instance, physical intimate partner violence was reported by 17 per cent of Finnish women, while the EU average was 9 per cent, with only 3 countries reporting higher rates. The corresponding figure for non-partner violence was 10 for Finland and 6 for EU average, placing Finland second highest in violence rates of the 30 countries. It is also noteworthy that the share of ever-partnered women reporting physical injuries from partner violence was comparatively high in Finland [@eurostat2025]. Although multiple sources indicate a comparatively high prevalence of violence against women in Finland, it is possible that these findings are at least partially attributable to methodological issues in data collection and other related factors [see @humbert_undoing_2021]. Alternative or supplementary hypotheses include high levels of equality placing women at greater risk of violence; and/or high levels of education expanding the perception of conflicts to be considered as violence, and hence reporting of incidents in surveys also being higher.

The Finnish Crimes Against Businesses survey of 2018 suggested that the Finnish retail sector suffers from a higher risk of shoplifting and violence against employees than its Dutch and UK counterparts [@saarikkomäki2019].

## Youth crime surveys

Findings in adult populations cannot necessarily be generalised to youths. The most recent international criminological youth survey is the third sweep of the International Self-Report Delinquency Study (ISRD-3), targeting 13–16-year-olds. Its report shows last year’s crime prevalence rates for 22 European countries, with measurements in selected big cities between 2012 and 2015 [@enzmann2018]. In that study, Finland’s ranking varied according to different types of victimisations. In robbery victimisation, Finland had the highest prevalence in Europe, while in assault victimisation, only 18 % of the comparison countries had lower victimisation prevalence than Finland. Thus, it appears that violent behaviour against youths in Finnish cities was expressed as robberies in 2012-2013. The offenders were typically slightly older youths, with over-representation among persons identified by the victims as being of non-Finnish origin [@kivivuori2014].

The Health Behaviour in School Aged Children survey (HBSC), operated by the World Health Organization, corroborates the low Finnish assault/violence victimisation prevalence. In 2018, only 12 per cent of the 43 comparison countries manifested a lower prevalence rate of fighting among 15-year-olds than Finland [@inchley_enhancing_2020].

In ISRD3, Finland also ranked relatively high in theft victimisation, as 86 per cent of the comparison countries had lower last-year prevalence. The same applied to hate crime victimisation (73 % of comparison countries with lower rates). Thus, with the exception of assault/violence, the Finnish youth victimisation rates have been above average in European comparison, as revealed by international self-report surveys.

Overall, comparative surveys among adults converge to suggest that violence and threats are more prevalent in Finland than could be predicted solely from living standards and the welfare state regime. At least in the 1990s, theft prevalence was below most comparison countries. It is unfortunate that the International Crime Victim Surveys were discontinued after 2005.

In contrast, Finnish youths do not appear to suffer from heightened risk of violence, except for robbery. Relatively high violence victimisation rates among adults, as suggested by international crime surveys, could also reflect methodological factors, such as more honest responding in victim surveys, or cultural factors, such as broader concepts of violence applied by the respondents [@kivivuori2014]. However, homicide rate comparisons are consistent with survey-based findings on violence, thus validating each other. It appears to be possible to tentatively suggest that in European comparison, Finland’s violence problem may also extend to non-lethal and ‘everyday’ violence among adults, but not among youths.
